apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fvozmew9w-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fvozmew9w-nodejs 
  name: fvozmew9w-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fvozmew9w-nodejs 
